//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maxsys.VisualLAL
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "vlal";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"VisualLAL";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"Maxsys";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.1.1.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID VisualLALDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(VisualLALCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID VisualLALExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(VisualLALCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewVisualLALExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(VisualLALCommandSetId), 0x0001);
	
		// Package identifier
		public const string VisualLALPackageId = "92b8be84-5876-454a-a110-d7663866aacd";
		
		// Editor factory identifier
		public const string VisualLALEditorFactoryId = "54f7a544-5de7-4c80-9687-6bbfdcd6251f";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string VisualLALModelExplorerToolWindowId = "3c234f57-6ad8-4db1-8b0c-07ae6f348283";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace Maxsys.VisualLAL
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string VisualLALCommandSetId = "c943e9c4-af87-42b2-bc07-1910caa25bc9";
	}
}